### ISSUE TITLE
Please bring back --filelist functionality

### ISSUE THREAD

**Issue by arkdae** [jomiq/i3-wpd#1]
This tool used to work with a file which contains the name of the images, in order, which should appear on each consecutive desktop. I would provide --file-list (now feh removed the third -) and that was all that was needed. Please bring this back, as I have images in different formats, and in addition, I do not want to rename the images 1jpg 2jpg, etc. to get them loaded properly. The image list file has all necessary information.

**Comment by jomiq** [comment]
Can you provide an example of how you would call `i3-wpd` using `—file-list`? I’m not familiar with the function and can’t figure out why it would work in the first place.

**Comment by arkdae** [comment]
I have this at the end of .config/i3/config:

exec /opt/i3-wpd/i3wpd.py --bg black --bg-scale --file-list ~/.config/i3wpd.list

And i3wpd.list looks like this:

~/images/joeyjazz-space-nebula-artwork-digital-art-stars-abstract-2560x1600.png
~/images/352b60d69d5fe212c4a51c1731d08ed0.jpg
~/images/d97b712f8e34cde99d8d59863124a76d.jpg

This computer was in storage for a while, and after I brought it out, I found that it was too old to update Arch Linux, so I rebuilt it. Of course all my configuration remained in my home directory. So the above worked at least back in 2017 or 2018.

Investigating this further, I found that the ~ does not work, so I have to put the full path to the image files. Then I see from the feh man page that it takes the command --filelist, without a dash between the words. With this change at least the first image shows up as a background, but then feh complains as I switch desktops because it seems to be called with file names such as 1png, 2png, etc. to change the image, instead of what's provided in the list.

**Comment by arkdae** [comment]
Looking at your Git history, it does not look like much has changed. Perhaps this is due to a change in feh.

**Comment by jomiq** [comment]
Yes that is probably the case. I’m still a bit confused why it worked in the first place. 

A reasonable implementation would be to make the script accept a list of filenames on the command line and then users could just pipe that from a file if they want. Would that be ok?

**Comment by arkdae** [comment]
That would work just fine for me.

**Comment by arkdae** [comment]
I just stumbled across an old tab in my web browser where I commented on this script, "Thanks a lot. I took this Python script, modified it so that I can provide the name of a text file which lists the exact image files I want to use, and then added it as an exec to the end of my I3 config."

So that explains how I had it working before. Sorry I had totally forgotten that I even did that.

**Comment by jomiq** [comment]
Lol. I’ll see if I get around to this or you could make a PR.
